<?php

//novo

if(isset($_POST["nome"])):
global $wpdb;

$nome = $_POST["nome"];
$descricao = $_POST["descricao"];
$categoria = $_POST["tipoevento"];
$dataevento = $_POST["dataevento"];
$horario = $_POST["horario"];
$local = $_POST["local"];
$datatermino = $_POST["datatermino"];
$valor = $_POST["valor"];
$contadeposito = $_POST["contadeposito"];
$banco = $_POST["banco"];
$emailcomprovante = $_POST["emailcomprovante"];
$prazopagamento =  $_POST["prazopagamento"];
$faixaetaria = $_POST["faixaetaria"];
$vagas = $_POST["vagas"];
$emailcontato = $_POST["emailcontato"];
$observacoes = $_POST["observacoes"];
$telefonecontato = $_POST["telefonecontato"];

$datacriacao = date("Y-m-d");
$usuario = "";
$codigoespecifico = "";

if(stripos($dataevento, "/") !== false){
$dataevento = substr($dataevento, 6, 4)."-".substr($dataevento, 3, 2)."-".substr($dataevento, 0, 2);
$datatermino = substr($datatermino, 6, 4)."-".substr($datatermino, 3, 2)."-".substr($datatermino, 0, 2);
$prazopagamento = substr($prazopagamento, 6, 4)."-".substr($prazopagamento, 3, 2)."-".substr($prazopagamento, 0, 2);
}

$uploadedfile = $_FILES['imagem'];

$upload_overrides = array( 'test_form' => false );

$movefile = wp_handle_upload( $uploadedfile, $upload_overrides );

if ( $movefile && ! isset( $movefile['error'] ) ) {
    echo "File is valid, and was successfully uploaded.\n";
    var_dump( $movefile );
} else {
    /**
     * Error generated by _wp_handle_upload()
     * @see _wp_handle_upload() in wp-admin/includes/file.php
     */
    echo $movefile['error'];
}

$banco = strtoupper($banco);

$inserir_dados_evento = $wpdb->query(" 
    INSERT INTO  `wordpress`.`wp1_eventos` (
    `id` ,
    `nome` ,
    `categoria` ,
    `descricao` ,
    `data` ,
    `hora` ,
    `local` ,
    `data_termino` ,
    `imagem` ,
    `valor` ,
    `conta_deposito` ,
    `banco` ,
    `email_comprovante` ,
    `prazo_pagamento` ,
    `faixa_etaria` ,
    `vagas` ,
    `email_contato` ,
    `telefone_contato` ,
    `observacoes`
    )
    VALUES (
    NULL ,  '$nome',  '$categoria',  '$descricao',  '$dataevento',  '$horario',  '$local',  '$datatermino',  '".$movefile['url']."',  '$valor',  '$contadeposito',  '$banco',  '$emailcomprovante',  '$prazopagamento',  '$faixaetaria',  '$vagas',  '$emailcontato', '$telefonecontato',  '$observacoes'
    );")or die($wpdb->error);

$id = $wpdb->insert_id;

$criartabela = $wpdb->query("CREATE TABLE IF NOT EXISTS {$wpdb->prefix}evento_$id ( 
id int(11) NOT NULL AUTO_INCREMENT, 
nome varchar(255) NOT NULL,
data_nascimento date NOT NULL,
sexo varchar(1) NOT NULL,
email varchar(100) NOT NULL,
telefone varchar(25) NOT NULL,
whatsapp`varchar(25) NOT NULL,
pagamento varchar(50) NOT NULL COMMENT '1, 2, 3 parcelas ou ok',  
status varchar(50) NOT NULL COMMENT 'lista de espera',  
PRIMARY KEY (id) ) 
ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;");

endif;


?>